robot:
  hint: "ToDo for robot generator part"
  robot_name: "test_robot"
  # How many Links do you want to create?
  link_count: "2"
  #please copy this part depending on the number of links you want to create
  link_id: "1"
  link_name: "link1"
  link_id: "2"
  link_name: "link2"
  #end of link part
world:
  robot:
    type: "ur5"
    position:
      x: 0
      y: 0.8
      z: 1.25
    rotation:
      r: 0
      p: 0
      y: 0
    sensors:
      # - type: "lidar"
      #   link: 3
      #   position:
      #     x: 0
      #     y: 0
      #     z: .1
      #   rotation:
      #     r: 0
      #     p: 0
      #     y: 0
      #   params:
      #     ray_min: .02
      #     ray_max: 2
      #     ray_num_ver: 6
      #     ray_num_hor: 6
      - type: "lidar"
        link: 6
        position:
          x: 0
          y: 0
          z: .12
        rotation:
          r: 0
          p: 90
          y: 0
        params:
          ray_min: .02
          ray_max: 2
          ray_num_ver: 3
          ray_num_hor: 12
  obstacles:
    - type: "table/table"
      position:
        x: 0
        y: 0
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      scale : 2
    #- type: "maze"
    #  position:
    #    x: 3
    #    y: 0
    #    z: 0
    #  rotation:
    #    r: 0
    #    p: -90
    #    y: 0
    #  params:
    #    width: 6
    #    height: 9
    #    wall_width: .1
    #    wall_height: .5
    #    wall_thickness: .01
    #    difficulty: .5
    #    connector_strict: True
    #    connector_probability: .1
    #    connector_height: .25
    - type: "goal"
      position:
        x: 0
        y: 0
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 0
      scale: 1.5
    - type: "human"
      position:
        x: 0
        y: 0
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      scale: 1.5
      params:
        move:
          - position:
              x: -2
              y: 2
              z: 1.4
          #- position:
          #    x: -2
          #    y: -2
          #    z: 1.4
          #- position:
          #    x: 2
          #    y: -2
          #    z: 1.5
          - position:
              x: 2
              y: 2
              z: 1.5
    - type: "human_static"
      position:
        x: 1.6
        y: 0
        z: 1.4
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 1.5
    - type: "rectangle"
      moving: 1
      steps: 200
      start_pos:
        x: -1.5
        y: 0.3
        z: 1.5
      end_pos:
        x: -0.5
        y: 0.3
        z: 1.5
      position:
        x: -0
        y: -1.2
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 0.3
    - type: "rectangle"
      moving: 1
      steps: 200
      start_pos:
        x: -1.5
        y: -0.3
        z: 1.5
      end_pos:
        x: -0.5
        y: -0.3
        z: 1.5
      position:
        x: -0
        y: -1.2
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 0.3



