robot:
  hint: "ToDo for robot generator part"
world:
  robot:
    type: "kuka_kr210_support"
    position:
      x: 0
      y: 0
      z: 0
    rotation:
      r: 0
      p: 0
      y: 0
    sensors:
      - type: "lidar"
        link: 6
        position:
          x: 0
          y: 0
          z: .1
        rotation:
          r: 0
          p: 0
          y: 0
        params:
          ray_min: .02
          ray_max: 2
          ray_num_ver: 6
          ray_num_hor: 6
      - type: "lidar"
        link: 3
        position:
          x: 0
          y: 0
          z: .12
        rotation:
          r: 0
          p: 0
          y: 0
        params:
          ray_min: .02
          ray_max: 2
          ray_num_ver: 6
          ray_num_hor: 6
  obstacles:
    - type: "maze"
      position:
        x: -7
        y: -7
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      params:
        width: 12
        height: 12
        unit_size: .4
        wall_width: .05
        wall_height: .65
        difficulty: 1
    - type: "cube"
      position:
        x: 2
        y: 2
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0