robot:
  hint: "ToDo for robot generator part"
  robot_name: "test_robot"
  # How many Links do you want to create?
  link_count: "2"
  #please copy this part depending on the number of links you want to create
  link_id: "1"
  link_name: "link1"
  link_id: "2"
  link_name: "link2"
  #end of link part
world:
  robot:
    type: "ur5"
    position:
      x: 0
      y: 0.8
      z: 1.25
    rotation:
      r: 0
      p: 0
      y: 0
    sensors:
      # - type: "lidar"
      #   link: 3
      #   position:
      #     x: 0
      #     y: 0
      #     z: .1
      #   rotation:
      #     r: 0
      #     p: 0
      #     y: 0
      #   params:
      #     ray_min: .02
      #     ray_max: 2
      #     ray_num_ver: 6
      #     ray_num_hor: 6
      - type: "lidar"
        link: 6
        position:
          x: 0
          y: 0
          z: -3
        rotation:
          r: 0
          p: 90
          y: 0
        params:
          ray_min: .02
          ray_max: 2
          ray_num_ver: 3
          ray_num_hor: 12
  goals:
    - indicator: "sphere"
      position:
        x: 0
        y: 0
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 0
      scale: 1.5
  obstacles:
    - type: "table/table"
      position:
        x: 0
        y: 0
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      scale : 2
    - type: "maze"
      position:
        x: 3
        y: 0
        z: 0
      rotation:
        r: 0
        p: -90
        y: 0
      params:
        rows: 9
        cols: 6
        element_size: .1
        element_depth: .5
        wall_thickness: .01
        difficulty: .5
        connector_strict: True
        connector_probability: .1
        connector_height: .25
    - type: "shelf"
      position:
        x: 0
        y: 0
        z: 0
      rotation:
        r: 0
        p: -90
        y: 0
      params:
        move:
          - position:
              x: -2
              y: 2
              z: 1.4
          - position:
              x: 2
              y: 2
              z: 1.5
        rows: 9
        cols: 6
        element_size: .2
        shelf_depth: .5
        wall_thickness: .01
    - type: "human"
      position:
        x: 0
        y: 0
        z: 0
      rotation:
        r: 0
        p: 0
        y: 0
      scale: 1.5
      params:
        move:
          - position:
              x: -2
              y: 2
              z: 1.4
          - position:
              x: 2
              y: 2
              z: 1.5
    - type: "human"
      position:
        x: 1.6
        y: 0
        z: 1.4
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 1.5
    - type: "rectangle"
      position:
        x: -0
        y: -1.2
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 0.3
      params:
        move:
          - steps: 200
            position:
              x: -2
              y: .2
              z: 1.4
          - steps: 100
            position:
              x: 2
              y: .2
              z: 1.5
          - steps: 100
            position:
              x: 2
              y: 1.2
              z: 1.5
    - type: "rectangle"
      position:
        x: -0
        y: -1.2
        z: 1.5
      rotation:
        r: 0
        p: 0
        y: 90
      scale: 0.3
      params:
        move:
          - steps: 200
            position:
              x: -1.5
              y: -0.3
              z: 1.5
          - steps: 200
            position:
              x: -0.5
              y: -0.3
              z: 1.5



